[package]
name = "foreman-agent"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.51.0"
# serde needed for parsing milestones
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
