[package]
name = "supervisor"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = { version = "0.51.0", default-features = false, features = [
    "std",
] }
